### ISSUE TITLE
Saber spawns at angle 

### ISSUE THREAD

**Issue by RedBrumbler** [RedBrumbler/Qosmetics#13]
Allegedly sabers spawn with a bit of a rotated offset, even though their models are rotated to 0, 0, 0

Perhaps define a rotation offset to fix this

**Comment by Sp00nb0b-cyber** [comment]
yes

**Comment by RedBrumbler** [comment]
Testing in game showed that the saber is in fact straight in the hand, just the quest 2 controllers are not straight and thus this is not an issue that can be solved. The sabers are correctly spawned along the length of the handle itself

**Comment by RedBrumbler** [comment]
This might be an issue only for quest 1, further investigation is required

**Comment by RedBrumbler** [comment]
Testing showed that the saber is in fact not at an angle, but is completely at the same angle as the base game saber, thus this is not an issue to be fixed by qosmetics

[Quest 2 video](https://streamable.com/87xeh1)

[Quest 1 video](https://streamable.com/85dzop)
