### ISSUE TITLE
compatibility issues

### ISSUE THREAD

**Issue by Number1AnimeGirl** [RedBrumbler/Qosmetics#18]
some of the old sabers / bloq are not working like TrueAccBloqV2V1.0.0 they won't appear in the qosmetic menu.

**Comment by RedBrumbler** [comment]
Are these by bobbie

**Comment by Number1AnimeGirl** [comment]
?

**Comment by RedBrumbler** [comment]
did bobbie make them
also are you installing zips or raw .qbloq files when you say these don't work

**Comment by Number1AnimeGirl** [comment]
.zip

**Comment by RedBrumbler** [comment]
well zips are no longer used for single installs, you need to unzip it

closing this issue since it's not an issue with the mod itself

**Comment by Number1AnimeGirl** [comment]
oh ok i didn't know that
