### ISSUE TITLE
Lag and loss of feedback.

### ISSUE THREAD

**Issue by ShaseDK** [RedBrumbler/Qosmetics#19]
Hi. Thank you for this great mod. Really love the possibility to change my sabers. I have used the mod on Quest 2 for a few days, and I have encountered a few problems, with the katana sword.

First it seems to lag a bit, compared to the default sabers. Not much, but enough to make me miss nodes in faster paced songs.

Secondly I have tried two times, that my right controller looses the vibrating feedback, in middle of a song. Feedback only returns on restart of the unit.

**Comment by RedBrumbler** [comment]
New update should perform better
