### ISSUE TITLE
Qosmetics constantly crashing Beat Saber.

### ISSUE THREAD

**Issue by mBotCode** [RedBrumbler/Qosmetics#20]
When I first open beatsaber, I can go into the qosmetics settings tab fine, and change the saber. But when I try to open the qosmetics menu after playing a level, it usually crashes beat saber. If it does not it makes the game extremely unstable, and it starts to crash at random times.

**Comment by RedBrumbler** [comment]
can't help it, this is kinda the way quest mods are due to c# objects getting moved/cleaned up by GC
