### ISSUE TITLE
qosmetics settings wont show up in options

### ISSUE THREAD

**Issue by spIoopy** [RedBrumbler/Qosmetics#23]
so i installed the latest qosmetics and enabled it but it wont show in the options

**Comment by RedBrumbler** [comment]
This is not an issue with the mod itself, rather with the installation of it, closing this issue

**Comment by MythicVR** [comment]
i have the same problem do you know a fix yet?

**Comment by The24Kings** [comment]
As red stated above this is not an issue with the mod itself, you can use the quest-help channels in Beat Saber Modding Group to get it resolved
