### ISSUE TITLE
Will this be updated for the new BMBF?

### ISSUE THREAD

**Issue by mathsmathsmaths** [RedBrumbler/Qosmetics#25]
So the asset loader is being removed in the new BMBF so I'm curious about how installing qsabers, qwalls, and qblocs will work

**Comment by ComputerElite** [comment]
Qosmetics is a hook mod. It'll still work as before since it doesn't **change** game assets but instead **loads** them into the game on top of the base game assets.

**Comment by mathsmathsmaths** [comment]
Right but with the asset loader being removed, how will Qosmetics load assets?

**Comment by ComputerElite** [comment]
not asset loaders are removed. asset swapping is being removed from bmbf. it's a differece if you load assets into the game or if you replace the base game assets before the game starts. Qosmetics will work just like before.

**Comment by mathsmathsmaths** [comment]
So, I’m confused... is the asset loader the thing that you drag and drop stuff into on your pc or am I mistaken?

**Comment by ComputerElite** [comment]
it doesn't matter? Qosmetics will still load all your sabers, walls and bloqs. Just menu titles won't work since those are asset mods. If Qosmetic loads them in it'll work again but for now since BMBF will not modify the game assets anymore they won't work

**Comment by mathsmathsmaths** [comment]
Well how will you load new sabers and walls? How was it done in BMBF for 1.13.2?

**Comment by ComputerElite** [comment]
BMBF just copied your sabers, walls and bloqs to a location where Qosmetics looks for them. Then Qosmetics loads them into the game

**Comment by mathsmathsmaths** [comment]
And what steps does the player take? Is it also a drag and drop? I thought that was being removed. I truly know nothing about BMBF since I have never modded.

**Comment by ComputerElite** [comment]
Assets mods involve BMBF modifying files. The thig qsabers use is just copying (BMBF has a file in which stands which file type goes to which location). That will not be removed

**Comment by mathsmathsmaths** [comment]
Ohhh I see. So pretty much nothing changes. Thanks.

**Comment by ComputerElite** [comment]
You're welcome
