### ISSUE TITLE
Game constantly crashing after Health and Safety with Qosmetics enabled on 1.16.4

### ISSUE THREAD

**Issue by eeveeishpowered** [RedBrumbler/Qosmetics#31]
With Qosmetics enabled, I constantly crash after the health and safety menu. I found this out through process of elimination of enabling and disabling mods.

I have all the core mods installed and enabled, alongside AikaTweaks and Chroma.
Heres a logcat log I captured of me opening the game and it crashing after the health and safety menu. Hope it helps.
[log.txt](https://github.com/RedBrumbler/Qosmetics/files/7024477/log.txt)
Heres the respective tombstone file as well (well according to the logs it's related to the crash)
[tombstone_02.txt](https://github.com/RedBrumbler/Qosmetics/files/7024486/tombstone_02.txt)

**Comment by RedBrumbler** [comment]
![image](https://user-images.githubusercontent.com/51795403/130304109-6c977e50-92cf-405c-8f4f-e648801587a1.png)
this is not related to qosmetics, so it's addressed to the wrong github :)

**Comment by eeveeishpowered** [comment]
Strange, the logcat mentioned something about that tombstone after the crash, didn't know that it was related to something else.

**Comment by RedBrumbler** [comment]
the stacktrace is what tells you what is related, the logcat itself is just all logs
