### ISSUE TITLE
Custom Walls not working.

### ISSUE THREAD

**Issue by a-randomdev** [RedBrumbler/Qosmetics#43]
When I open the page up and try to equip sabers and notes, it works fine in game, but with custom walls, it equips them fine, but when I get in game, it is just regular walls.

**Comment by george0513** [comment]
Do you have Noodle Extensions installed? NE normally disables custom walls on Qosmetics to increase performance on Noodle maps.

**Comment by a-randomdev** [comment]
that must be it.
