### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by BeatChamp** [RedBrumbler/Qosmetics#45]
Update it to 1.20.0

**Comment by RetardNuggets** [comment]
Can you not open requests like this? It's not an issue and clogs up the git logs. You already know Red is working hard to get this mod updated, not to mention none of the modders have any obligation to continue what they do. Please, be patient, and frequently check the announcement channels for any new information regarding Qosmetics.

**Comment by RedBrumbler** [comment]
Unhelpful
