### ISSUE TITLE
Can we get an update to 1.24?

### ISSUE THREAD

**Issue by riskable** [RedBrumbler/Qosmetics#51]
Seems like 1.24 is the new "stable" releases of Beat Saber that everyone's upgrading to.  Qosmetics is one of the few mods that hasn't been ported yet.  Would it be possible to get it updated?

The mod is awesome and I appreciate your efforts! :+1:

**Comment by BoogieHasFun** [comment]
the mod is basically being re-done / optimized, dont open not useful issues and think of "soon™️

**Comment by RedBrumbler** [comment]
as mentioned before it's been worked on already, thus this issue is a non-issue and will be closed

**Comment by riskable** [comment]
Sorry, I had no idea.  I looked at the commits and hadn't seen anything in a while.  That's all.  Keep up the good work :+1:
