### ISSUE TITLE
Crash when pointers go Invalid

### ISSUE THREAD

**Issue by RedBrumbler** [RedBrumbler/Qosmetics#7]
For some reason using tricksaber crashes with qosmetics, but we are unsure as to why and can't reliably reproduce the bug

**Comment by ComputerElite** [comment]
I think it's just like any mod. It works for some and for some others it doesn't. For me Tricksaber and qosmetics work together.

**Comment by RedBrumbler** [comment]
I no longer think its tricksaber and actuslly just a crash within qosmetics itself

**Comment by RedBrumbler** [comment]
hopefully fixed in 1.1.0
