### ISSUE TITLE
Potential cheating issue relating to Ghost Notes and Disappearing Arrows with custom notes 

### ISSUE THREAD

**Issue by othereevee** [RedBrumbler/Qosmetics#9]
The Ghost Notes and Disappearing Arrows modifiers do not work on custom notes (the note just stays the same with the modifiers on, unless disappearing arrows still works with notes that have default arrows enabled ), which could create possible cheating issues where a custom note user can use these modifiers for a higher score without any visual change to the notes.
It probably isn't fixable (unless you do some wacky score disabling tricks) and isn't really a major issue but in some cases it can be unfair to others.

**Comment by RedBrumbler** [comment]
since scores get disabled in [this method](https://github.com/RedBrumbler/Qosmetics/blob/2b01ec30ab08b7ebe4aed712a8154bb2ac5be05a/include/Qosmetic/QuestNote.hpp#L63) this is a non-issue

**Comment by othereevee** [comment]
Thanks
